### ISSUE TITLE
Discrepancy history table view

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#196] opened 2019-07-15 19:55 UTC
the step number is shown in the column header of discrepancy table view, which is better not.
![Screen Shot 2019-07-15 at 2 53 02 PM](https://user-images.githubusercontent.com/3741779/61244771-96090680-a710-11e9-8ade-904bf59d46b1.png)

As shown in the image, the "0.1label" should be "label"

**Comment by dongliu** [comment] 2019-07-20 18:30
I think it is a duplication of https://github.com/AdvancedPhotonSource/traveler/issues/190 which was fixed.

**Comment by shengb** [comment] 2019-07-21 00:06
I remember that. It seems that with recent changes, the same issue comes back again.
Maybe there was something wrong during merging, and this could be a quick fix?

**Comment by dongliu** [comment] 2019-07-21 05:49
I cannot reproduce it. I suspect you might use a form that was saved before the fix of https://github.com/AdvancedPhotonSource/traveler/issues/190 . The fix is in the model and applies when a form is saved. you can check mongodb to verify, or just create a traveler with a new form.

**Comment by dongliu** [comment] 2019-12-21 17:28
please try to reproduce it on the latest master. We can close it if it is not there anymore.

**Closed** 2020-02-06 13:49 UTC
Labels: enhancement
